
service: node-code-challenge

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

  environment:
    githubUrl: 'https://api.github.com/repos'


functions:
  fetchPullRequests:
    handler: src/handlers/fetch.handler
    events:
      - http:
          path: /open-prs
          method: GET